Support for Certificate Pinning in Omise Swift
chakrit/omise-swift pull request #27
Opened 2016-10-13 08:41 UTC by pitiphong-p

2016-10-13 08:50 UTC, chakrit requested changes

2016-10-13 08:50 UTC, chakrit commented on OmiseSwift/Client.swift
> +                creditial = nil
`credential`

2016-10-13 08:50 UTC, chakrit commented on OmiseSwift/Config.swift
> +    public let pinningSignature: Data?
I think we should just hide this completely, hard-code the certs.

2016-10-13 10:20 UTC, pitiphong-p commented on OmiseSwift/Config.swift
> +    public let pinningSignature: Data?
I hide this signature in the Client now

2016-10-13 10:21 UTC, pitiphong-p commented on OmiseSwift/Client.swift
> +                creditial = nil
Thank you

2016-10-14 06:54 UTC, chakrit approved these changes
👍

2016-11-21 03:08 UTC, merged