Infinite scroll
chakrit/omise-swift pull request #30
Opened 2016-11-18 10:04 UTC by pitiphong-p

This PR introduces the new data structure that will handle the `Infinite Scroll` or `Load More` logic

2016-11-21 03:26 UTC, chakrit submitted a review, later dismissed

2016-11-21 03:26 UTC, chakrit commented on OmiseSwift/List.swift
> + import Foundation
whitespace ☝️

2016-11-21 03:26 UTC, chakrit commented on OmiseSwift/List.swift
> +    }
Can some of these properties be made `private set` or immutable?

2016-11-21 03:26 UTC, chakrit commented on OmiseSwift/Listable.swift
> +    }
☝️ Can this use `Failable.map`?

2016-11-21 03:27 UTC, chakrit commented
ตาลาย 😵

2016-11-21 05:11 UTC, pitiphong-p commented on OmiseSwift/Listable.swift
> +    }
I think we can use that. This closure will call the given callback not to convert it though

2016-11-21 05:14 UTC, pitiphong-p commented on OmiseSwift/List.swift
> +    }
That's a good catch. Thank you
BTW I already fixed it

2016-11-25 08:24 UTC, chakrit requested changes

2016-11-25 08:24 UTC, chakrit commented on OmiseSwift/Listable.swift
> +    }
:trollface:

2016-11-25 08:24 UTC, chakrit commented on OmiseSwift/Listable.swift
> +        }
can `.map` here and (the loadPrevious method) too I think ☝️

2016-11-25 08:48 UTC, pitiphong-p commented
Thank you and fixed 🙇

2016-11-28 05:29 UTC, pitiphong-p commented on OmiseSwift/Listable.swift
> +    }
Fixed :)

2016-11-28 05:29 UTC, pitiphong-p commented on OmiseSwift/Listable.swift
> +        }
Fixed :)

2016-11-29 07:04 UTC, chakrit approved these changes

2016-12-02 05:19 UTC, igroomgrim approved these changes
👍  🔮

2016-12-02 05:24 UTC, merged